/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.mine.sweeper;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.*;

/**
 *
 * @author Famas
 */
public class MineSweeper extends javax.swing.JFrame {

    /**
     * Creates new form MineSweeperView
     */
    public MineSweeper() {
        initComponents();
        
        setSize(520,500);
        
        reset_button = new JButton("Reset");
        reset_button.setBounds(0, 0, 75, 50);
        reset_button.setFocusPainted(false);
        
        reset_button.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                resetMatrix();
            }
        });
                
        getContentPane().add(reset_button);
        
        initMatrix();
    }
    
    private JButton reset_button;
    private JButton[][] button_matrix;
    private String[][] current_map;
    
    // Si el string tiene el formato <numero><-><numero>
    // Ejemplo: 18-34
    // Devuelve en la posicion 0 : 18
    // Devuelve en la posicion 1 : 34
    // Separa por coordenada (x, y)
    private int[] getCoord(String coord){
        coord += "-";
        
        int k = 0;
        int[] coords = new int[2];
        String current_number = "";
        for(int i = 0; i < coord.length(); ++i){
            if(coord.charAt(i) == '-'){
                coords[k++] = Integer.parseInt(current_number);
                current_number = "";
            } else {
                current_number += coord.charAt(i);
            }
        }
        return coords;
    }
    
    private void resetMatrix(){
        for(int i = 0; i < 10; ++i){
            for(int j = 0; j < 8; ++j){
                button_matrix[i][j].setText("");
            }
        }
    }
    
    private void initMatrix(){
        button_matrix = new JButton[18][32];
        current_map = new String[18][32];
        
        int x = 0;
        int y = 0;
        for(int i = 0; i < 10; ++i){
            y = 55;
            for(int j = 0; j < 8; ++j){
                button_matrix[i][j] = new JButton("");
                button_matrix[i][j].setBounds(x, y, 50, 50);
                button_matrix[i][j].setFocusPainted(false);
                button_matrix[i][j].setName(i + "-" + j);
                
                current_map[i][j] = String.valueOf(i + j);
                    
                button_matrix[i][j].addActionListener(new ActionListener() {
                    @Override
                    public void actionPerformed(ActionEvent e) {
                        JButton jb = (JButton)e.getSource();
                        int[] coord = getCoord(jb.getName());
                        
                        System.out.println(current_map[coord[0]][coord[1]]);
                        
                        // TODO: Aqui va lo tuyo alcor
                        jb.setText(current_map[coord[0]][coord[1]]);
                    }
                });
                
                getContentPane().add(button_matrix[i][j]);
                
                y += 50;
            }
            x += 50;
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setSize(new java.awt.Dimension(0, 0));
        getContentPane().setLayout(null);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MineSweeper.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MineSweeper.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MineSweeper.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MineSweeper.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MineSweeper().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
